### ISSUE TITLE
Dropdown event list GET from EventBrite limited to first page results (50) only.

### ISSUE THREAD

**Issue by kojis** [twomice/com.joineryhq.eventbrite#34]
Wondering if anyone else has encountered this and already found a solution?

Optimally, the solution would iterate through the pages of potential events, or provide a search qualifier to limit the results.

I tried a few quick hack attempts to filter by active state or future dates, but could not seem to get this to filter, it just seems to return the first 50 results it gets.

Any insight appreciated.  thank you

**Comment by MegaphoneJon** [comment]
@kojis Is this the same issue that this PR fixes? https://github.com/twomice/com.joineryhq.eventbrite/pull/19

**Comment by kojis** [comment]
Looks like it, thank you for the update-
