### ISSUE TITLE
Ignore Billing Address creation in Civi if Street Address is blank

### ISSUE THREAD

**Issue by josephlacey** [twomice/com.joineryhq.eventbrite#7]
EventBrite includes the billing state and country in all orders even though there's no associated billing record, e.g. in pay later scenarios or attendees paid for by other attendees.

**Comment by twomice** [comment]
@josephlacey I've closed this ticket with commit  d416ccd, but you may want to double-check and re-open if needed. 

One note: with this commit, we're ignoring any address (billing or any other type) that omits the stree_address component.

**Comment by josephlacey** [comment]
> @josephlacey I've closed this ticket with commit [d416ccd](https://github.com/twomice/com.joineryhq.eventbrite/commit/d416ccdbddf5917ac161b828849cccdf50c606aa), but you may want to double-check and re-open if needed.

Yep, looks good.

> One note: with this commit, we're ignoring any address (billing or any other type) that omits the stree_address component.

I'd say this is fine.
