### ISSUE TITLE
Make Ticket Type sync configuration stricter

### ISSUE THREAD

**Issue by josephlacey** [twomice/com.joineryhq.eventbrite#8]
EventBrite configurations allow for Hidden ticket types that in some cases don't need to be sync'ed over to Civi.  Currently if there's no configuration mapping for a ticket type in EventBrite, the sync will create a record in Civi without an attendee role.  We should ignore Ticket Types if there's no mapped Attendee Role.

**Comment by twomice** [comment]
@josephlacey Fixed as discussed in MatterMost:

> solve this by calculating the contribution total_amount and fee_amount based on the sum of appropriate amounts for each non-ignored Attendee in the Order (whereas at present we just take those amounts from the Order itself.) 

Closing as believed fixed; please re-open as needed.
